[package]
name = "SQP-client"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.9.0-alpha.2"
log = "0.4.22"
env_logger = "0.11.5"
tempfile = "3.16.0"
